### ISSUE TITLE
navigator.share not defined

### ISSUE THREAD

**Issue by shdq2** [benkaiser/web-share-images#2]
Thanks for sharing this project.

I want to use a web share image, but it says navigator.share is not defined. Is there any special treatment for this part?

**Comment by benkaiser** [comment]
G'day!

Could be a couple of things, the browser only exposes the API in secure contexts (HTTPS), are you loading your site via HTTPS?

Also, it's only supported on some platforms (mainly mobile, windows and mac. I have a feeling Linux isn't supported): https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share#browser_compatibility
